### ISSUE TITLE
CSS 수정 및 코드 리팩토링

### ISSUE THREAD

**Issue by mic050r** [mic050r/InnerFlow#15]
### ✅ TODO
- [x] 목표 생성폼 css 수정
- [x] 목표 todo list css 수정
- [x] 성취일지 페이지 css 수정
- [x] 성취일지 생성폼 css 수정
- [x] 익명게시판 css 수정
- [x] 익명게시판 생성폼 css 수정
- [x] 익명게시판 디케일 페이지 css 수정
- [x] footer에 링크 추가하기
