### ISSUE TITLE
코드 리팩토링 및 수정사항

### ISSUE THREAD

**Issue by mic050r** [mic050r/InnerFlow#21]
### ✅ TODO
- [x] view 파일 분리
- [x] model 파일 분리
- [ ] 태그 부분(엔터 누르면 추가되도록 + /로 분리)
- [ ] 오늘의 온도 진행바 색 수정
- [ ] todo 부분에서 삭제와 수정 폼 css 수정 
- [ ] 답변 수정 폼 css 수정 
- [ ] 홈에 가면증후군 관련 아티클 추가
- [ ] input창 focus할 때 테두리 색 수정
- [ ] 검색한 게시판 없으면 없다는 문구 추가
- [ ] 목표 진행상황 할 일 수 css 수정
